image: golang:1.17

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    pip3: /root/.cache/pip
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build

  services:
    docker:
      memory: 2048

  steps:
    - step: &lint-test-sonarcloud
        name: Run Linter and Unit Tests push results to SonarCloud
        caches:
          - sonar
        size: 2x
        services:
          - docker
        script:
          - echo "${DOCKER_NETRC}" > ~/.netrc
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1
          - make lint
          - make ci-test
          - pipe: sonarsource/sonarcloud-scan:1.3.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}

pipelines:

  default:

    - step: *lint-test-sonarcloud

  tags:
    '*':

      - step: *lint-test-sonarcloud

      - step:
          name: Slack Report
          deployment: Production
          script:
            - chmod +x scripts/slack.sh
            - >
              ./scripts/slack.sh 
              "Toolbox Repository Release" 
              "Release tag: ${BITBUCKET_TAG},,Require in go.mod,github.com/toolbox ${BITBUCKET_TAG}" 
              0
